### ISSUE TITLE
where do you get the gmat

### ISSUE THREAD

**Issue by liaocs2008** [lorenlugosch/neural-min-sum-decoding#1]
Hi,

Nice work!

I see that you have H matrix in alist format. I am trying to work on a standard data set, i.e., https://www.uni-kl.de/channel-codes and only find they have H matrix. 

May I ask where do you get your gmat file? 

Thanks!

**Comment by lorenlugosch** [comment]
Thanks! Unfortunately I don't remember how I got the gmat files... maybe they used to be on that website.
